stages:
  - build
  - deploy

variables:
  PROGECT: a-music-new
  APP: backend-deposit
  COMPONENT_NAME: $APP
  DOCKER_BUILDKIT: 1
  TRANSFER_METER_FREQUENCY: "2s"
  GIT_DEPTH: 0


build:
  stage: build
  tags: [shell-dev]
  before_script:
    - echo "$AND_DOCKER_REGISTRY_RW_PASS" | docker login -u nexus "$AND_DOCKER_REGISTRY" --password-stdin
  script:
    - docker build --tag $AND_DOCKER_REGISTRY_NAME/$PROGECT-$APP:dev -f Dockerfile --build-arg BUILDKIT_INLINE_CACHE=1 .
    - docker push $AND_DOCKER_REGISTRY_NAME/$PROGECT-$APP:dev
  only:
    - devops_deploy

deploy:
  stage: deploy
  tags: [shell-dev]
  variables:
    COMPOSE_PROJECT_NAME: $PROGECT
  before_script:
    - echo "$AND_DOCKER_REGISTRY_RO_PASS" | docker login -u nexus-ro "$AND_DOCKER_REGISTRY" --password-stdin
  script:
    - docker stop $PROGECT-$APP-dev || true
    - docker rm $PROGECT-$APP-dev || true
    - docker rmi -f $AND_DOCKER_REGISTRY_NAME/$PROGECT-$APP:dev || true
   # - docker image prune -f || true
    - docker-compose -f docker-compose.yaml pull
    - docker-compose -f docker-compose.yaml up --force-recreate -d
  only:
    - devops_deploy
