spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: serg
    password: 12345
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true
        ddl-auto: none
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    username: a.music.platform@gmail.com
    password: project-a-music
    port: 587
    properties.mail.smtp:
      auth: true
      starttls.enable: true

logging:
  level:
    org:
      hibernate:
        type: TRACE


security:
  token:
    secret: secret
    expiration: 3600000 # это 1 час в мс по формуле 1(час) * 60(мин) * 60(сек) * 1000(мс)
  code-expiration: 2
